-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.applications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  name text NOT NULL,
  display_name text NOT NULL,
  description text,
  forms jsonb NOT NULL DEFAULT '[]'::jsonb,
  app_config jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  slug text,
  CONSTRAINT applications_pkey PRIMARY KEY (id),
  CONSTRAINT applications_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.bulk_document_transcripts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  document_id uuid NOT NULL UNIQUE,
  job_id uuid NOT NULL,
  full_transcript text NOT NULL,
  page_transcripts jsonb DEFAULT '[]'::jsonb,
  section_index jsonb DEFAULT '{}'::jsonb,
  field_locations jsonb DEFAULT '{}'::jsonb,
  total_pages integer,
  total_sections integer,
  generation_time_ms integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT bulk_document_transcripts_pkey PRIMARY KEY (id),
  CONSTRAINT bulk_document_transcripts_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.bulk_jobs(id),
  CONSTRAINT bulk_document_transcripts_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.bulk_job_documents(id)
);
CREATE TABLE public.bulk_extracted_fields (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  document_id uuid NOT NULL,
  job_id uuid NOT NULL,
  field_name text NOT NULL,
  field_label text,
  field_type character varying NOT NULL,
  field_value text,
  field_group text,
  confidence_score numeric,
  page_number integer,
  extraction_method character varying,
  extraction_timestamp timestamp with time zone DEFAULT now(),
  tokens_used integer,
  processing_time_ms integer,
  model_version character varying,
  validation_status character varying DEFAULT 'pending'::character varying,
  needs_manual_review boolean DEFAULT false,
  validation_errors jsonb,
  review_notes text,
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  bounding_box jsonb,
  field_metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  field_order integer,
  section_name text,
  source_location text,
  extraction_context text,
  CONSTRAINT bulk_extracted_fields_pkey PRIMARY KEY (id),
  CONSTRAINT bulk_extracted_fields_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.bulk_job_documents(id),
  CONSTRAINT bulk_extracted_fields_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.bulk_jobs(id),
  CONSTRAINT bulk_extracted_fields_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES auth.users(id)
);
CREATE TABLE public.bulk_job_documents (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  job_id uuid NOT NULL,
  source_path text NOT NULL,
  filename character varying NOT NULL,
  file_size bigint,
  mime_type character varying,
  document_type character varying,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'queued'::character varying, 'processing'::character varying, 'completed'::character varying, 'failed'::character varying, 'needs_review'::character varying]::text[])),
  priority integer DEFAULT 3 CHECK (priority >= 1 AND priority <= 5),
  retry_count integer DEFAULT 0,
  max_retries integer DEFAULT 3,
  error_message text,
  error_type character varying,
  worker_id character varying,
  created_at timestamp with time zone DEFAULT now(),
  queued_at timestamp with time zone,
  processing_started_at timestamp with time zone,
  processing_completed_at timestamp with time zone,
  extraction_time_seconds double precision,
  token_usage jsonb,
  cost_inr double precision,
  extracted_data_id uuid,
  extracted_data_table character varying,
  total_fields_extracted integer DEFAULT 0,
  fields_needing_review integer DEFAULT 0,
  average_confidence numeric,
  processing_time_ms integer,
  total_tokens_used integer,
  processing_stage character varying,
  pages_processed integer DEFAULT 0,
  total_pages integer DEFAULT 0,
  CONSTRAINT bulk_job_documents_pkey PRIMARY KEY (id),
  CONSTRAINT bulk_job_documents_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.bulk_jobs(id)
);
CREATE TABLE public.bulk_jobs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  user_id uuid,
  source_type character varying NOT NULL CHECK (source_type::text = ANY (ARRAY['folder'::character varying, 'database'::character varying, 'cloud'::character varying]::text[])),
  source_config jsonb NOT NULL,
  processing_config jsonb NOT NULL,
  processing_options jsonb NOT NULL,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'running'::character varying, 'paused'::character varying, 'completed'::character varying, 'failed'::character varying, 'stopped'::character varying]::text[])),
  total_documents integer DEFAULT 0,
  processed_documents integer DEFAULT 0,
  failed_documents integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  updated_at timestamp with time zone DEFAULT now(),
  template_id character varying,
  CONSTRAINT bulk_jobs_pkey PRIMARY KEY (id),
  CONSTRAINT bulk_jobs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.bulk_manual_review_queue (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  document_id uuid NOT NULL,
  job_id uuid NOT NULL,
  reason text NOT NULL,
  error_message text,
  error_type character varying,
  priority integer DEFAULT 3 CHECK (priority >= 1 AND priority <= 5),
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'in_review'::character varying, 'resolved'::character varying, 'reprocessed'::character varying]::text[])),
  assigned_to uuid,
  review_notes text,
  reviewed_at timestamp with time zone,
  reviewed_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT bulk_manual_review_queue_pkey PRIMARY KEY (id),
  CONSTRAINT bulk_manual_review_queue_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.bulk_job_documents(id),
  CONSTRAINT bulk_manual_review_queue_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.bulk_jobs(id),
  CONSTRAINT bulk_manual_review_queue_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES auth.users(id),
  CONSTRAINT bulk_manual_review_queue_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES auth.users(id)
);
CREATE TABLE public.bulk_processing_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  job_id uuid,
  document_id uuid,
  level character varying NOT NULL CHECK (level::text = ANY (ARRAY['info'::character varying, 'warning'::character varying, 'error'::character varying, 'debug'::character varying]::text[])),
  message text NOT NULL,
  log_metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT bulk_processing_logs_pkey PRIMARY KEY (id),
  CONSTRAINT bulk_processing_logs_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.bulk_jobs(id),
  CONSTRAINT bulk_processing_logs_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.bulk_job_documents(id)
);
CREATE TABLE public.document_chunks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  document_id uuid NOT NULL,
  chunk_index integer NOT NULL,
  chunk_text text NOT NULL,
  chunk_embedding USER-DEFINED,
  token_count integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT document_chunks_pkey PRIMARY KEY (id),
  CONSTRAINT document_chunks_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.documents(id)
);
CREATE TABLE public.document_fields (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  document_id uuid,
  field_name text NOT NULL,
  field_type text DEFAULT 'text'::text,
  field_value text,
  confidence numeric DEFAULT 0,
  position jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT document_fields_pkey PRIMARY KEY (id),
  CONSTRAINT document_fields_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.documents(id)
);
CREATE TABLE public.document_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  document_type text NOT NULL,
  version text NOT NULL DEFAULT '1.0'::text,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'active'::text, 'archived'::text])),
  fields jsonb NOT NULL DEFAULT '[]'::jsonb,
  field_count integer NOT NULL DEFAULT 0,
  usage_count integer NOT NULL DEFAULT 0,
  accuracy_score numeric DEFAULT 0,
  is_public boolean DEFAULT false,
  sample_document_url text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_by text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT document_templates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.document_workflows (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  document_id uuid,
  workflow_name text NOT NULL,
  current_step integer DEFAULT 1,
  total_steps integer NOT NULL,
  status text DEFAULT 'pending'::text,
  assignee text,
  due_date timestamp with time zone,
  workflow_data jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT document_workflows_pkey PRIMARY KEY (id),
  CONSTRAINT document_workflows_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.processed_documents(id)
);
CREATE TABLE public.documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  file_name text NOT NULL,
  file_type text NOT NULL,
  file_size bigint NOT NULL,
  storage_path text NOT NULL,
  original_url text,
  upload_source text DEFAULT 'manual'::text,
  processing_status text DEFAULT 'pending'::text CHECK (processing_status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'failed'::text])),
  analysis_result jsonb DEFAULT '{}'::jsonb,
  extracted_text text,
  confidence_score numeric DEFAULT 0,
  template_id uuid,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  vector_embedding USER-DEFINED,
  document_type text,
  CONSTRAINT documents_pkey PRIMARY KEY (id),
  CONSTRAINT documents_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT documents_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.document_templates(id)
);
CREATE TABLE public.extracted_data (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  document_id uuid NOT NULL,
  template_id uuid,
  field_id text NOT NULL,
  field_label text NOT NULL,
  field_type text NOT NULL,
  extracted_value text,
  confidence_score numeric DEFAULT 0,
  position_data jsonb DEFAULT '{}'::jsonb,
  validation_status text DEFAULT 'pending'::text CHECK (validation_status = ANY (ARRAY['pending'::text, 'valid'::text, 'invalid'::text, 'needs_review'::text])),
  manually_corrected boolean DEFAULT false,
  corrected_value text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT extracted_data_pkey PRIMARY KEY (id),
  CONSTRAINT extracted_data_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.documents(id),
  CONSTRAINT extracted_data_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.document_templates(id)
);
CREATE TABLE public.extraction_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  template_id character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  description text,
  document_type character varying,
  bank character varying,
  version character varying DEFAULT '1.0'::character varying,
  extraction_instructions text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT extraction_templates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.form_submissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  template_id uuid,
  form_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'draft'::text,
  submitted_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  form_name text NOT NULL,
  completion_percentage numeric DEFAULT 0,
  CONSTRAINT form_submissions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.mapping_templates (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  name character varying NOT NULL,
  description text,
  document_type character varying,
  excel_columns jsonb NOT NULL,
  field_mappings jsonb NOT NULL,
  sample_file_name character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  usage_count integer DEFAULT 0,
  CONSTRAINT mapping_templates_pkey PRIMARY KEY (id),
  CONSTRAINT mapping_templates_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.processed_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  template_id uuid,
  original_filename text NOT NULL,
  storage_path text NOT NULL,
  processed_data jsonb DEFAULT '{}'::jsonb,
  confidence_score numeric DEFAULT 0,
  status text DEFAULT 'processing'::text,
  processing_steps jsonb DEFAULT '[]'::jsonb,
  extracted_text text,
  raw_ocr_data jsonb DEFAULT '{}'::jsonb,
  document_metadata jsonb DEFAULT '{}'::jsonb,
  processing_metadata jsonb DEFAULT '{}'::jsonb,
  search_vector tsvector,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT processed_documents_pkey PRIMARY KEY (id),
  CONSTRAINT processed_documents_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.document_templates(id)
);
CREATE TABLE public.public_form_submissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  public_form_id uuid NOT NULL,
  user_id uuid,
  form_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  submitted_at timestamp with time zone DEFAULT now(),
  submitter_email text,
  submitter_name text,
  ip_address inet,
  user_agent text,
  CONSTRAINT public_form_submissions_pkey PRIMARY KEY (id),
  CONSTRAINT public_form_submissions_public_form_id_fkey FOREIGN KEY (public_form_id) REFERENCES public.public_forms(id)
);
CREATE TABLE public.public_forms (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  template_id uuid,
  form_config jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_active boolean NOT NULL DEFAULT true,
  requires_auth boolean NOT NULL DEFAULT false,
  allow_multiple_submissions boolean NOT NULL DEFAULT true,
  submission_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  form_title text NOT NULL,
  form_description text,
  public_url_slug text UNIQUE,
  success_message text DEFAULT 'Thank you for your submission!'::text,
  CONSTRAINT public_forms_pkey PRIMARY KEY (id)
);
CREATE TABLE public.template_columns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  template_id character varying,
  column_number integer NOT NULL,
  excel_column character varying NOT NULL,
  source_page character varying,
  source_section character varying,
  source_field character varying,
  source_table_row character varying,
  source_keyword character varying,
  extraction_hint text,
  default_value character varying,
  post_process_type character varying,
  post_process_config jsonb,
  db_field_path character varying,
  required boolean DEFAULT false,
  validation_regex character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  search_keywords ARRAY,
  data_type character varying DEFAULT 'text'::character varying,
  extraction_strategy character varying DEFAULT 'direct'::character varying,
  example_value text,
  confidence_threshold numeric DEFAULT 0.5,
  CONSTRAINT template_columns_pkey PRIMARY KEY (id),
  CONSTRAINT template_columns_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.extraction_templates(template_id)
);
CREATE TABLE public.template_performance_metrics (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  template_id character varying NOT NULL,
  document_id uuid NOT NULL,
  total_columns integer NOT NULL,
  mapped_columns integer DEFAULT 0,
  unmapped_columns integer DEFAULT 0,
  low_confidence_columns integer DEFAULT 0,
  average_confidence numeric,
  mapping_success_rate numeric,
  transcript_generation_time_ms integer,
  mapping_time_ms integer,
  total_processing_time_ms integer,
  errors jsonb DEFAULT '[]'::jsonb,
  warnings jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT template_performance_metrics_pkey PRIMARY KEY (id),
  CONSTRAINT template_performance_metrics_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.extraction_templates(template_id),
  CONSTRAINT template_performance_metrics_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.bulk_job_documents(id)
);
CREATE TABLE public.template_usage_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  template_id uuid NOT NULL,
  user_id uuid NOT NULL,
  document_name text,
  confidence_score numeric,
  fields_matched integer DEFAULT 0,
  total_fields integer DEFAULT 0,
  analysis_metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT template_usage_logs_pkey PRIMARY KEY (id),
  CONSTRAINT template_usage_logs_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.document_templates(id)
);
CREATE TABLE public.templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  document_type text NOT NULL DEFAULT 'General'::text,
  version text NOT NULL DEFAULT '1.0'::text,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'active'::text, 'archived'::text])),
  fields jsonb NOT NULL DEFAULT '[]'::jsonb,
  field_count integer NOT NULL DEFAULT 0,
  usage_count integer NOT NULL DEFAULT 0,
  accuracy_score numeric DEFAULT 0,
  is_public boolean NOT NULL DEFAULT false,
  document_image text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT templates_pkey PRIMARY KEY (id),
  CONSTRAINT templates_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);