// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Load from Vite environment variables with fallbacks
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://uajyetwarydyvjazopko.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhanlldHdhcnlkeXZqYXpvcGtvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk5MTc4MjMsImV4cCI6MjA3NTQ5MzgyM30.A5cvvAZQE59KfvbGlrwzk9xodS9-HyerWj4v72wRv04';

if (!import.meta.env.VITE_SUPABASE_URL || !import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY) {
  console.warn('[Supabase] Using fallback values for Supabase configuration');
  console.warn('[Supabase] SUPABASE_URL:', import.meta.env.VITE_SUPABASE_URL ? 'From env' : 'Using fallback');
  console.warn('[Supabase] SUPABASE_PUBLISHABLE_KEY:', import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ? 'From env' : 'Using fallback');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
